name: Tests
permissions:
  checks: write

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    name: pytest (${{ matrix.python-version }})
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: test_ege_user
          POSTGRES_PASSWORD: test_pass
          POSTGRES_DB: ege_cards_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          -- heatlh-start-period: 30s
          -- heatlh-start-interval: 5s
          -- heatlh-interval: 30s
          -- heatlh-timeout: 5s
          -- heatlh-retries: 8

    strategy:
      matrix:
        python-version: ['3.12']

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
        with:
          enable-cache: true
          cache-dependency-glob: uv.lock

      - name: Setup project environment
        run: uv sync --locked --dev --all-extras

      - name: Run migrations
        run: uv run alembic upgrade head
        env:
          DATABASE_URL: postgresql+asyncpg://test_ege_user:test_pass@localhost:5432/ege_cards_test

      - name: Run tests
        run: uv run pytest --verbose --color=yes --durations=10 --junitxml=junit.xml

      - name: Publish test results
        if: always()
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          files: junit.xml
